### ISSUE TITLE
Not is secret xD :v

### ISSUE THREAD

**Issue by Jhair2015** [AJS-development/Project-Nehemiah#4]

**Comment by Andrews54757** [comment]
#1 . 

@Jhair2015  I warned everyone that you cannot make fake issues. And you just did that. Really, you literally defied me when it clearly says to do elsewise. for others who see this. see what happened to @Jhair2015  as I am going to make an example of him


OFFENSE:
> Making fake issues


Today I hereby declare you BANNED from AJS **indefinatly**
> Banned on 10/8/16

**Comment by Andrews54757** [comment]
THE BAN HAMMER HAS SPOKEN

**Comment by ThunderGemios10** [comment]
@Andrews54757 How dafuq can you ban someone from a repo.. (OH WAIT, Is there a block option now?)

**Comment by Andrews54757** [comment]
Yes, and there has been for a loooong time
