### ISSUE TITLE
Socket API

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Project-Nehemiah#7]
Hello all, I am posting the socket apis. You may use these to create your own client. But remember, it won't work with servers that have the secure connection feature on
# Overview

Server to client:

| Event | Purpose |
| --- | --- |
| hello | First thing that is sent |
| accepted | After the socket connection is secured, this is sent |
| kicked | Sent on kick |
| mes | Main message packet |
| updatepos | Spectating packet |
| rip | sent on death |
| nodes | Used to send nodes |
| delnodes | node deletion |
| cha | change server packet |

Client to server

| Event | Purpose |
| --- | --- |
| cha | Used to change servers |
| mes | main message packet |
| mouse | used to send the mouse |
# Documentation
### hello

First thing that is sent. It sends a object using RSON

```
{
msg: "Achieved Connection", // message to say
secure: true, // if secure connections are enabled or not
version: "2.0.0" // server version
}
```
### accepted

What the server sends if the socket is established. Sends a string

```
"welcome to the server" // msg to say
```
### kicked

Sent when the server kicks. Sends a string

```
"you are using profanity!" // kicked reason
```
### mes

Main message packet. Uses RSON. Sends an object

```
{
type: "addNode",  // type of action
. . . // more
}
```

**Can send:**

Note that `data` is the object it sends

| Name | description |
| --- | --- |
| addNode | Used to set a node as the current player node. Uses data.id |
| clearNodes | Used to clear nodes |
| showOverlay | Used to show overlay |
| setBorder | Used to set the game borders. Uses data.bounds |
| chat | used to send chat msgs |
### rip

Sent when a player dies. Sends an object using RSON

```
{
alive: 1032383, // time alive in milisec
killerId: 3 // player id of killer. Used to draw revenge icon
}
```
### nodes

Sends nodes. Uses RSON. Is an array. 
#### What each item in the array contains

**General. Only sent once unless the node changes** 

| Name | Description |
| --- | --- |
| id | Nodeid |
| owId | Ownerid |
| size | node radius |
| mass | node mass |
| type | node type. Numerical |
| name | node name |
| color | node color |
| skin | node skin |
| posX | position X |
| posY | position Y |
| spiked | Spiked |
| agit | agitated |

**Moving. Sent when an object moves**

| Name | Description |
| --- | --- |
| moveUpt | NodeID |
| x | x position |
| y | y position |

**RemoveFromScreen. Sent when a moving node goes off screen**

| Name | Description |
| --- | --- |
| remove | nodeID |
### delnodes

Sent to delete nodes. Sends an array in RSON

```
[
{
id: 3, // nodeid being deleted
killer: 2, // nodeid of killer
},
{
id: 4, // nodeid being deleted
killer: 6, // nodeid of killer
},
{
id: 1, // nodeid being deleted
killer: 5, // nodeid of killer
}
]
```
### mes

Main message packet. Sends an object in RSON

```
{
type: "play",  // type of action
. . . // more
}
```

**Can send:**

Note that `data` is the object it sends

| Name | description |
| --- | --- |
| play | Sent when the player clicks play |
| chat | Sends chat msg |
| key | Sent when the user presses a key. Sends the keyid using data.id |
### mouse

Sends the players mouse coords. Sends a string

```
"1283|2083" // x|y
```

**Comment by SharkFinPro** [comment]
ill make one sometiem :D

**Comment by MasonBurdette** [comment]
Couldn't one use these for botting?

**Comment by Andrews54757** [comment]
No, they can't with servers using Socket Protection

**Comment by Andrews54757** [comment]
Every connection is secured if using the official clients

**Comment by LegitSoulja** [comment]
What happen to megabyte? @Andrews54757

**Comment by Andrews54757** [comment]
Sockets are different now

**Comment by MasonBurdette** [comment]
@Andrews54757 is it due to your project no longer using RSON?

**Comment by Andrews54757** [comment]
That and another thing
